---
- name: Listen for events on a webhook
  hosts: all

  ## Define our source for events

  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  ## Define the conditions we are looking for

  rules:
    - name: look for interface config
      condition: event.payload.message is regex("Configure interfaces on leaf[0-4]", ignorecase=true)
      # condition: event.payload.message == "Ansible is super cool"
      action:
        run_playbook:
          name: interfaces.yml
